CREATE TABLE LOGIN(USERNAME CHAR(3), PASS_WORD CHAR(6));
INSERT INTO LOGIN (USERNAME, PASS_WORD) VALUES ('CO1', 'PASS01');
INSERT INTO LOGIN (USERNAME, PASS_WORD) VALUES ('CO2', 'PASS02');
INSERT INTO LOGIN (USERNAME, PASS_WORD) VALUES ('CO3', 'PASS03');
INSERT INTO LOGIN (USERNAME, PASS_WORD) VALUES ('CO4', 'PASS04');
INSERT INTO LOGIN (USERNAME, PASS_WORD) VALUES ('CO5', 'PASS05');
SELECT * FROM LOGIN;